2025-09-04 19:02:06,089 - manual_client_0 - INFO - Starting client 0 connecting to 20.169.237.127:8080
2025-09-04 19:02:09,940 - manual_client_0 - INFO - Client 0 initialized with 6115 training samples
2025-09-04 19:02:09,940 - manual_client_0 - INFO - Client 0 ready. Connecting to server...
2025-09-04 19:02:09,940 - flwr - WARNING - DEPRECATED FEATURE: flwr.client.start_client() is deprecated.
	Instead, use the `flower-supernode` CLI command to start a SuperNode as shown below:

		$ flower-supernode --insecure --superlink='<IP>:<PORT>'

	To view all available options, run:

		$ flower-supernode --help

	Using `start_client()` is deprecated.

            This is a deprecated feature. It will be removed
            entirely in future versions of Flower.
        
2025-09-04 19:02:09,967 - flwr - DEBUG - Opened insecure gRPC connection (no certificates were passed)
2025-09-04 19:02:09,970 - flwr - DEBUG - ChannelConnectivity.IDLE
2025-09-04 19:02:09,970 - flwr - DEBUG - ChannelConnectivity.CONNECTING
2025-09-04 19:02:10,456 - flwr - DEBUG - ChannelConnectivity.READY
2025-09-04 19:02:10,703 - flwr - INFO - 
2025-09-04 19:02:10,704 - flwr - INFO - Received: get_parameters message 7bff149b-d686-4aee-ac54-dbf8bad276ec
2025-09-04 19:02:10,719 - manual_client_0 - INFO - Client 0 applied Label Flip Attack (intensity=0.1, source=None, target=None)
2025-09-04 19:02:10,725 - flwr - INFO - Sent reply
2025-09-04 19:04:06,319 - flwr - INFO - 
2025-09-04 19:04:06,321 - flwr - INFO - Received: train message d9c55557-1e2b-4509-86ad-0ac995ec62e1
2025-09-04 19:04:07,271 - flwr - ERROR - Client raised an exception.
Traceback (most recent call last):
  File "/Users/hanafemira/development/FL_CognitiveDefence/fl_config/lib/python3.13/site-packages/flwr/compat/client/app.py", line 466, in start_client_internal
    reply_message = client_app(message=message, context=context)
  File "/Users/hanafemira/development/FL_CognitiveDefence/fl_config/lib/python3.13/site-packages/flwr/client/client_app.py", line 144, in __call__
    return self._call(message, context)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/Users/hanafemira/development/FL_CognitiveDefence/fl_config/lib/python3.13/site-packages/flwr/client/client_app.py", line 128, in ffn
    out_message = handle_legacy_message_from_msgtype(
        client_fn=client_fn, message=message, context=context
    )
  File "/Users/hanafemira/development/FL_CognitiveDefence/fl_config/lib/python3.13/site-packages/flwr/client/message_handler/message_handler.py", line 128, in handle_legacy_message_from_msgtype
    fit_res = maybe_call_fit(
        client=client,
        fit_ins=recorddict_to_fitins(message.content, keep_input=True),
    )
  File "/Users/hanafemira/development/FL_CognitiveDefence/fl_config/lib/python3.13/site-packages/flwr/client/client.py", line 224, in maybe_call_fit
    return client.fit(fit_ins)
           ~~~~~~~~~~^^^^^^^^^
  File "/Users/hanafemira/development/FL_CognitiveDefence/fl_config/lib/python3.13/site-packages/flwr/client/numpy_client.py", line 227, in _fit
    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore
  File "/Users/hanafemira/development/FL_CognitiveDefence/src/clients/enhanced_client.py", line 69, in fit
    attacked_dataset = self.attack.attack_data(self.trainloader.dataset, self.client_id)
  File "/Users/hanafemira/development/FL_CognitiveDefence/src/attacks/label_flip.py", line 43, in attack_data
    available_classes.remove(labels[idx].item())
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
ValueError: list.remove(x): x not in list
2025-09-04 19:04:07,441 - flwr - DEBUG - gRPC channel closed
2025-09-04 19:04:07,442 - manual_client_0 - ERROR - Client 0 failed: list.remove(x): x not in list
2025-09-04 19:04:52,750 - manual_client_0 - INFO - Starting client 0 connecting to 20.169.237.127:8080
2025-09-04 19:04:56,670 - manual_client_0 - INFO - Client 0 initialized with 6115 training samples
2025-09-04 19:04:56,670 - manual_client_0 - INFO - Client 0 ready. Connecting to server...
2025-09-04 19:04:56,670 - flwr - WARNING - DEPRECATED FEATURE: flwr.client.start_client() is deprecated.
	Instead, use the `flower-supernode` CLI command to start a SuperNode as shown below:

		$ flower-supernode --insecure --superlink='<IP>:<PORT>'

	To view all available options, run:

		$ flower-supernode --help

	Using `start_client()` is deprecated.

            This is a deprecated feature. It will be removed
            entirely in future versions of Flower.
        
2025-09-04 19:04:56,697 - flwr - DEBUG - Opened insecure gRPC connection (no certificates were passed)
2025-09-04 19:04:56,699 - flwr - DEBUG - ChannelConnectivity.IDLE
2025-09-04 19:04:56,700 - flwr - DEBUG - ChannelConnectivity.CONNECTING
2025-09-04 19:04:57,193 - flwr - DEBUG - ChannelConnectivity.READY
2025-09-04 19:04:59,656 - flwr - INFO - 
2025-09-04 19:04:59,656 - flwr - INFO - Received: evaluate message ce2e23bd-3229-41b5-a54c-6455e730d6c3
2025-09-04 19:05:06,071 - manual_client_0 - INFO - Client 0 Evaluation - Loss: 2.3058, Accuracy: 0.0900
2025-09-04 19:05:06,073 - flwr - INFO - Sent reply
2025-09-04 19:05:08,532 - flwr - INFO - 
2025-09-04 19:05:08,532 - flwr - INFO - Received: train message 6402f85c-4d93-410e-bd23-2c863143df12
2025-09-04 19:05:09,441 - flwr - ERROR - Client raised an exception.
Traceback (most recent call last):
  File "/Users/hanafemira/development/FL_CognitiveDefence/fl_config/lib/python3.13/site-packages/flwr/compat/client/app.py", line 466, in start_client_internal
    reply_message = client_app(message=message, context=context)
  File "/Users/hanafemira/development/FL_CognitiveDefence/fl_config/lib/python3.13/site-packages/flwr/client/client_app.py", line 144, in __call__
    return self._call(message, context)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/Users/hanafemira/development/FL_CognitiveDefence/fl_config/lib/python3.13/site-packages/flwr/client/client_app.py", line 128, in ffn
    out_message = handle_legacy_message_from_msgtype(
        client_fn=client_fn, message=message, context=context
    )
  File "/Users/hanafemira/development/FL_CognitiveDefence/fl_config/lib/python3.13/site-packages/flwr/client/message_handler/message_handler.py", line 128, in handle_legacy_message_from_msgtype
    fit_res = maybe_call_fit(
        client=client,
        fit_ins=recorddict_to_fitins(message.content, keep_input=True),
    )
  File "/Users/hanafemira/development/FL_CognitiveDefence/fl_config/lib/python3.13/site-packages/flwr/client/client.py", line 224, in maybe_call_fit
    return client.fit(fit_ins)
           ~~~~~~~~~~^^^^^^^^^
  File "/Users/hanafemira/development/FL_CognitiveDefence/fl_config/lib/python3.13/site-packages/flwr/client/numpy_client.py", line 227, in _fit
    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore
  File "/Users/hanafemira/development/FL_CognitiveDefence/src/clients/enhanced_client.py", line 69, in fit
    attacked_dataset = self.attack.attack_data(self.trainloader.dataset, self.client_id)
  File "/Users/hanafemira/development/FL_CognitiveDefence/src/attacks/label_flip.py", line 43, in attack_data
    available_classes.remove(labels[idx].item())
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
ValueError: list.remove(x): x not in list
2025-09-04 19:05:09,485 - flwr - DEBUG - gRPC channel closed
2025-09-04 19:05:09,485 - manual_client_0 - ERROR - Client 0 failed: list.remove(x): x not in list
2025-09-04 19:05:49,848 - manual_client_0 - INFO - Starting client 0 connecting to 20.169.237.127:8080
2025-09-04 19:05:53,811 - manual_client_0 - INFO - Client 0 initialized with 6115 training samples
2025-09-04 19:05:53,811 - manual_client_0 - INFO - Client 0 ready. Connecting to server...
2025-09-04 19:05:53,811 - flwr - WARNING - DEPRECATED FEATURE: flwr.client.start_client() is deprecated.
	Instead, use the `flower-supernode` CLI command to start a SuperNode as shown below:

		$ flower-supernode --insecure --superlink='<IP>:<PORT>'

	To view all available options, run:

		$ flower-supernode --help

	Using `start_client()` is deprecated.

            This is a deprecated feature. It will be removed
            entirely in future versions of Flower.
        
2025-09-04 19:05:53,833 - flwr - DEBUG - Opened insecure gRPC connection (no certificates were passed)
2025-09-04 19:05:53,836 - flwr - DEBUG - ChannelConnectivity.IDLE
2025-09-04 19:05:53,837 - flwr - DEBUG - ChannelConnectivity.CONNECTING
2025-09-04 19:05:54,328 - flwr - DEBUG - ChannelConnectivity.READY
2025-09-04 19:06:09,500 - flwr - INFO - 
2025-09-04 19:06:09,501 - flwr - INFO - Received: evaluate message 0ee4b744-22a3-43dc-a006-de1c04c49c4f
2025-09-04 19:06:12,765 - manual_client_0 - INFO - Client 0 Evaluation - Loss: 2.3058, Accuracy: 0.0900
2025-09-04 19:06:12,767 - flwr - INFO - Sent reply
2025-09-04 19:06:15,335 - flwr - INFO - 
2025-09-04 19:06:15,336 - flwr - INFO - Received: train message 6171c860-feb7-4415-b219-751ae9bf9551
2025-09-04 19:06:16,241 - flwr - ERROR - Client raised an exception.
Traceback (most recent call last):
  File "/Users/hanafemira/development/FL_CognitiveDefence/fl_config/lib/python3.13/site-packages/flwr/compat/client/app.py", line 466, in start_client_internal
    reply_message = client_app(message=message, context=context)
  File "/Users/hanafemira/development/FL_CognitiveDefence/fl_config/lib/python3.13/site-packages/flwr/client/client_app.py", line 144, in __call__
    return self._call(message, context)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/Users/hanafemira/development/FL_CognitiveDefence/fl_config/lib/python3.13/site-packages/flwr/client/client_app.py", line 128, in ffn
    out_message = handle_legacy_message_from_msgtype(
        client_fn=client_fn, message=message, context=context
    )
  File "/Users/hanafemira/development/FL_CognitiveDefence/fl_config/lib/python3.13/site-packages/flwr/client/message_handler/message_handler.py", line 128, in handle_legacy_message_from_msgtype
    fit_res = maybe_call_fit(
        client=client,
        fit_ins=recorddict_to_fitins(message.content, keep_input=True),
    )
  File "/Users/hanafemira/development/FL_CognitiveDefence/fl_config/lib/python3.13/site-packages/flwr/client/client.py", line 224, in maybe_call_fit
    return client.fit(fit_ins)
           ~~~~~~~~~~^^^^^^^^^
  File "/Users/hanafemira/development/FL_CognitiveDefence/fl_config/lib/python3.13/site-packages/flwr/client/numpy_client.py", line 227, in _fit
    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore
  File "/Users/hanafemira/development/FL_CognitiveDefence/src/clients/enhanced_client.py", line 69, in fit
    attacked_dataset = self.attack.attack_data(self.trainloader.dataset, self.client_id)
  File "/Users/hanafemira/development/FL_CognitiveDefence/src/attacks/label_flip.py", line 43, in attack_data
    available_classes.remove(labels[idx].item())
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
ValueError: list.remove(x): x not in list
2025-09-04 19:06:16,269 - flwr - DEBUG - gRPC channel closed
2025-09-04 19:06:16,269 - manual_client_0 - ERROR - Client 0 failed: list.remove(x): x not in list
2025-09-05 14:35:03,656 - manual_client_0 - INFO - Starting client 0 connecting to 20.169.237.127:8080
2025-09-05 14:35:07,693 - manual_client_0 - INFO - Client 0 initialized with 6115 training samples
2025-09-05 14:35:07,693 - manual_client_0 - INFO - Client 0 ready. Connecting to server...
2025-09-05 14:35:07,693 - flwr - WARNING - DEPRECATED FEATURE: flwr.client.start_client() is deprecated.
	Instead, use the `flower-supernode` CLI command to start a SuperNode as shown below:

		$ flower-supernode --insecure --superlink='<IP>:<PORT>'

	To view all available options, run:

		$ flower-supernode --help

	Using `start_client()` is deprecated.

            This is a deprecated feature. It will be removed
            entirely in future versions of Flower.
        
2025-09-05 14:35:07,725 - flwr - DEBUG - Opened insecure gRPC connection (no certificates were passed)
2025-09-05 14:35:07,726 - flwr - DEBUG - ChannelConnectivity.IDLE
2025-09-05 14:35:07,727 - flwr - DEBUG - ChannelConnectivity.CONNECTING
2025-09-05 14:35:08,297 - flwr - DEBUG - ChannelConnectivity.READY
2025-09-05 14:35:08,538 - flwr - INFO - 
2025-09-05 14:35:08,539 - flwr - INFO - Received: get_parameters message 859b5013-eb25-46e9-bc69-5ab056434d7b
2025-09-05 14:35:08,552 - manual_client_0 - INFO - Client 0 applied Label Flip Attack (intensity=0.1, source=None, target=None)
2025-09-05 14:35:08,558 - flwr - INFO - Sent reply
2025-09-05 14:37:55,785 - flwr - INFO - 
2025-09-05 14:37:55,786 - flwr - INFO - Received: train message 4cbb6260-6663-4b0a-9b18-7d166d5ae2a5
2025-09-05 14:37:56,700 - flwr - ERROR - Client raised an exception.
Traceback (most recent call last):
  File "/Users/hanafemira/development/FL_CognitiveDefence/fl_config/lib/python3.13/site-packages/flwr/compat/client/app.py", line 466, in start_client_internal
    reply_message = client_app(message=message, context=context)
  File "/Users/hanafemira/development/FL_CognitiveDefence/fl_config/lib/python3.13/site-packages/flwr/client/client_app.py", line 144, in __call__
    return self._call(message, context)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/Users/hanafemira/development/FL_CognitiveDefence/fl_config/lib/python3.13/site-packages/flwr/client/client_app.py", line 128, in ffn
    out_message = handle_legacy_message_from_msgtype(
        client_fn=client_fn, message=message, context=context
    )
  File "/Users/hanafemira/development/FL_CognitiveDefence/fl_config/lib/python3.13/site-packages/flwr/client/message_handler/message_handler.py", line 128, in handle_legacy_message_from_msgtype
    fit_res = maybe_call_fit(
        client=client,
        fit_ins=recorddict_to_fitins(message.content, keep_input=True),
    )
  File "/Users/hanafemira/development/FL_CognitiveDefence/fl_config/lib/python3.13/site-packages/flwr/client/client.py", line 224, in maybe_call_fit
    return client.fit(fit_ins)
           ~~~~~~~~~~^^^^^^^^^
  File "/Users/hanafemira/development/FL_CognitiveDefence/fl_config/lib/python3.13/site-packages/flwr/client/numpy_client.py", line 227, in _fit
    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore
  File "/Users/hanafemira/development/FL_CognitiveDefence/src/clients/enhanced_client.py", line 69, in fit
    attacked_dataset = self.attack.attack_data(self.trainloader.dataset, self.client_id)
  File "/Users/hanafemira/development/FL_CognitiveDefence/src/attacks/label_flip.py", line 43, in attack_data
    available_classes.remove(labels[idx].item())
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
ValueError: list.remove(x): x not in list
2025-09-05 14:37:56,890 - flwr - DEBUG - gRPC channel closed
2025-09-05 14:37:56,891 - manual_client_0 - ERROR - Client 0 failed: list.remove(x): x not in list
2025-09-05 14:39:02,963 - manual_client_0 - INFO - Starting client 0 connecting to 20.169.237.127:8080
2025-09-05 14:39:06,876 - manual_client_0 - INFO - Client 0 initialized with 6115 training samples
2025-09-05 14:39:06,876 - manual_client_0 - INFO - Client 0 ready. Connecting to server...
2025-09-05 14:39:06,876 - flwr - WARNING - DEPRECATED FEATURE: flwr.client.start_client() is deprecated.
	Instead, use the `flower-supernode` CLI command to start a SuperNode as shown below:

		$ flower-supernode --insecure --superlink='<IP>:<PORT>'

	To view all available options, run:

		$ flower-supernode --help

	Using `start_client()` is deprecated.

            This is a deprecated feature. It will be removed
            entirely in future versions of Flower.
        
2025-09-05 14:39:06,903 - flwr - DEBUG - Opened insecure gRPC connection (no certificates were passed)
2025-09-05 14:39:06,905 - flwr - DEBUG - ChannelConnectivity.IDLE
2025-09-05 14:39:06,906 - flwr - DEBUG - ChannelConnectivity.CONNECTING
2025-09-05 14:39:07,374 - flwr - DEBUG - ChannelConnectivity.READY
2025-09-05 14:39:32,300 - flwr - INFO - 
2025-09-05 14:39:32,302 - flwr - INFO - Received: evaluate message 62a77cc3-70b7-40c8-8554-e11030b414ad
2025-09-05 14:39:34,928 - manual_client_0 - INFO - Client 0 Evaluation - Loss: 2.3058, Accuracy: 0.0900
2025-09-05 14:39:34,928 - flwr - INFO - Sent reply
2025-09-05 14:39:54,209 - flwr - INFO - 
2025-09-05 14:39:54,210 - flwr - INFO - Received: train message 80339187-37ed-411c-9e4f-70cb912718bb
2025-09-05 14:39:55,134 - flwr - ERROR - Client raised an exception.
Traceback (most recent call last):
  File "/Users/hanafemira/development/FL_CognitiveDefence/fl_config/lib/python3.13/site-packages/flwr/compat/client/app.py", line 466, in start_client_internal
    reply_message = client_app(message=message, context=context)
  File "/Users/hanafemira/development/FL_CognitiveDefence/fl_config/lib/python3.13/site-packages/flwr/client/client_app.py", line 144, in __call__
    return self._call(message, context)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/Users/hanafemira/development/FL_CognitiveDefence/fl_config/lib/python3.13/site-packages/flwr/client/client_app.py", line 128, in ffn
    out_message = handle_legacy_message_from_msgtype(
        client_fn=client_fn, message=message, context=context
    )
  File "/Users/hanafemira/development/FL_CognitiveDefence/fl_config/lib/python3.13/site-packages/flwr/client/message_handler/message_handler.py", line 128, in handle_legacy_message_from_msgtype
    fit_res = maybe_call_fit(
        client=client,
        fit_ins=recorddict_to_fitins(message.content, keep_input=True),
    )
  File "/Users/hanafemira/development/FL_CognitiveDefence/fl_config/lib/python3.13/site-packages/flwr/client/client.py", line 224, in maybe_call_fit
    return client.fit(fit_ins)
           ~~~~~~~~~~^^^^^^^^^
  File "/Users/hanafemira/development/FL_CognitiveDefence/fl_config/lib/python3.13/site-packages/flwr/client/numpy_client.py", line 227, in _fit
    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore
  File "/Users/hanafemira/development/FL_CognitiveDefence/src/clients/enhanced_client.py", line 69, in fit
    attacked_dataset = self.attack.attack_data(self.trainloader.dataset, self.client_id)
  File "/Users/hanafemira/development/FL_CognitiveDefence/src/attacks/label_flip.py", line 43, in attack_data
    available_classes.remove(labels[idx].item())
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
ValueError: list.remove(x): x not in list
2025-09-05 14:39:55,299 - flwr - DEBUG - gRPC channel closed
2025-09-05 14:39:55,299 - manual_client_0 - ERROR - Client 0 failed: list.remove(x): x not in list
